Dev9
AndreiBakunovich/TAT-tasks pull request #1
Opened 2017-09-29 16:55 UTC by AndreiBakunovich

Programm finished.

2017-09-29 17:17 UTC, IgorKheidorov requested changes
Code style for C#, hard code

2017-09-29 17:17 UTC, IgorKheidorov commented on dev9/Dev9/Program.cs
> +            try {
Code style, this is C#, use 
method()
{
}
instead of
method(){
}

2017-09-29 17:17 UTC, IgorKheidorov commented on dev9/Dev9/Program.cs
> +            string path = @"c:\Users\source.txt";
hard code

2017-09-29 17:17 UTC, IgorKheidorov commented on dev9/Dev9/Program.cs
> +            if (rnd.Next(1, 3) == 1)
code style

2017-09-29 17:17 UTC, IgorKheidorov commented on dev9/Dev9/Replacer.cs
> +            for (int i = 0; i < recipientIntervalStart; i++)
bad idea to copy arrays

2017-09-29 17:17 UTC, IgorKheidorov commented on dev9/Dev9/Replacer.cs
> +
bad idea to copy arrays

2017-09-29 17:17 UTC, IgorKheidorov commented on dev9/Dev9/Replacer.cs
> +
bad idea to copy arrays

2017-09-29 17:35 UTC, AndreiBakunovich commented on dev9/Dev9/Program.cs
> +            string path = @"c:\Users\source.txt";
What did you mean exactly in this code?

2017-10-02 09:11 UTC, IgorKheidorov approved these changes

2017-10-02 09:11 UTC, IgorKheidorov commented on dev9/Dev9/Replacer.cs
> +    class Replacer
Better name StrinReplacer

2017-10-02 09:11 UTC, IgorKheidorov commented on dev9/Dev9/Program.cs
> +            lineOneInChar = lines[0].ToCharArray();
What for? you make too many unnecessary convertions from char to string and back, not effective

2017-10-03 13:25 UTC, merged